name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test --no-build -c Release --verbosity normal

    - name: Stage artifacts
      run: mkdir -p packages && cd $_ && mv $(find ../ -wholename *.nupkg) .

    - name: Upload artifacts
      uses: actions/upload-artifact@v2.2.4
      with:
        name: packages
        path: packages/*
        if-no-files-found: error

  publish:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: PROD

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2.0.8
      with:
        name: packages
        path: packages

    - name: Push packages
      run: dotnet nuget push ./packages/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
